In [37]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from word2number import w2n

In [2]:
df=pd.read_csv('linearmultivariable.csv')
df

area   beadroom  age   price
0   2600       3.0   20  550000
1   3000       4.0   15  565000
2   3200       NaN   18  610000
3   3600       3.0   30  595000
4   4000       5.0    8  760000

In [3]:
df.beadroom

0    3.0
1    4.0
2    NaN
3    3.0
4    5.0
Name: beadroom, dtype: float64

In [6]:
df.beadroom.median()

3.5

In [7]:
import math
median_beadroom=math.floor(df.beadroom.median())

In [8]:
median_beadroom


3

In [9]:
df.beadroom.fillna(median_beadroom)

0    3.0
1    4.0
2    3.0
3    3.0
4    5.0
Name: beadroom, dtype: float64

In [10]:
df.beadroom=df.beadroom.fillna(median_beadroom)
df

area   beadroom  age   price
0   2600       3.0   20  550000
1   3000       4.0   15  565000
2   3200       3.0   18  610000
3   3600       3.0   30  595000
4   4000       5.0    8  760000

In [20]:
reg=linear_model.LinearRegression()
reg.fit(df[['area ','beadroom','age']],df.price)

LinearRegression()

In [19]:
df.columns

Index(['area ', 'beadroom', 'age', 'price'], dtype='object')

In [21]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [22]:
reg.intercept_

383724.9999999998

In [23]:
testValue=(4000*137.25)+(-26025*5)+(-6825*760000)+383724.9999999998

In [24]:
testValue

-5186197400.0

In [25]:
reg.predict([[3000,3,40]])

E:\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([444400.])

In [26]:
reg.predict([[2500,4,5]])

E:\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([588625.])

In [33]:
#exercise

In [59]:
d=pd.read_csv('hiring.csv')
d

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [60]:
d.experience.fillna('zero')

0      zero
1      zero
2      five
3       two
4     seven
5     three
6       ten
7    eleven
Name: experience, dtype: object

In [62]:
d.experience=d.experience.fillna('zero')

In [63]:
d.experience = d.experience.apply(w2n.word_to_num)
d

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [64]:
d.columns

Index(['experience', 'test_score(out of 10)', 'interview_score(out of 10)',
       'salary($)'],
      dtype='object')

In [71]:
import math
median_test_score = math.floor(d['test_score(out of 10)'].mean())

In [73]:
d['test_score(out of 10)']=d['test_score(out of 10)'].fillna(median_test_score)

In [74]:
d

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [79]:
reg2=linear_model.LinearRegression()
reg2.fit(d[['experience','test_score(out of 10)','interview_score(out of 10)']],d['salary($)'])

LinearRegression()

In [81]:
reg2.predict([[2,9,6]])

E:\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53713.86677124])

In [82]:
reg2.predict([[12,10,10]])

E:\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([93747.79628651])

In [86]:
m=pd.read_csv('ex2linearRegression.csv')
m

experience  test score  interview score
0            0           0                6
1            1           1                4
2            2           3                7
3            3           5                9
4            4           6                6
5            5           9                3
6            6           4               10
7            7           8                2
8            8           8                5
9            9           9                9
10          10          10               10
11          11           5                6
12          12          10                9
13          13          10               10
14          14           9               10
15          15           8               10
16          16           9                9
17          17          10                9
18          18           9                7
19          19           9                9
20          20           9                8
21          21           9                9
22          22           9                8
23          23           9                7
24          24           8                9
25          25           9                9
26          26           9                7
27          27           8                7
28          28           9                9
29          29           7                8
30          30          10                9

In [89]:
predict=reg2.predict(m)

E:\lib\site-packages\sklearn\base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- interview score
- predicted salary
- test score
Feature names seen at fit time, yet now missing:
- interview_score(out of 10)
- test_score(out of 10)

  warnings.warn(message, FutureWarning)


ValueError: X has 4 features, but LinearRegression is expecting 3 features as input.